#!/usr/bin/python
from flask import Flask, jsonify
import random

app = Flask(__name__)

@app.route("/")
def hello():
    
    jokes = [
        ('If your American going into the bathroom and American when you come out, what are you in the bathroom?...','European.'),
        ('What did the fish say when he swam into a wall?...\n','Dam.')
    ]

    l_jokes = []
    for joke in jokes:
        l_jokes.append(
            {'setup':joke[0], 'punchline':joke[1]}
        )

    return jsonify(random.choice(l_jokes))


if __name__ == '__main__':
    app.run(debug=False,host='0.0.0.0',port='8090')

