#!/usr/bin/python
from flask import Flask
import random

app = Flask(__name__)

@app.route("/")
def hello():
    jokes = ['If your American going into the bathroom and American when you come out, what are you in the bathroom?...\nEuropean.', 'What did the fish say when he swam into a wall?...\nDam.']
    return random.choice(jokes)


if __name__ == '__main__':
    app.run(debug=False,host='0.0.0.0',port='8090')

